### PR TITLE
Restaurant menu and menu item details page 

### LINKED ISSUE #24: Ensure the menu includes images, food names, prices, restaurant names and country for each item

### PR DESCRIPTION
**Pull request by Hudamabkhoot**
Updates in this pull request:

- Created the Menu page to display restaurant menus dynamically fetched using useRouteLoaderData. 

- Integrated search functionality to filter menu items based on user input. 

- Implemented navigation to the Item details page to show detailed information about each menu item fetched from the data.

Fixes: #24

### CODE REVIEW

**Review by efezinoidisi — CHANGES_REQUESTED** [review]
Great job! 👏

I noticed the use of useEffect in the Menu and MenuItemsDetails component. I believe we might be able to achieve the same functionality without it.

Let me know your thoughts on this as well.

**Comment by Hudamabkhoot** [comment]
thanks for the feedback! 👍 

I agree with you on reconsidering the useEffect usage in Menu and MenuItemsDetails. I've already made the changes to achieve the same functionality without it.

**Review by efezinoidisi — APPROVED** [review]
Well done!

**Comment by ScaxCodes** [comment]
Great work!

**Pull request merged**
